version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 15
    commit-message:
      prefix: 'build(deps): '
      prefix-development: 'build(dev-deps): '
