version: 2.1

# ██████╗ ███████╗███████╗███████╗██████╗ ███████╗███╗   ██╗ ██████╗███████╗███████╗
# ██╔══██╗██╔════╝██╔════╝██╔════╝██╔══██╗██╔════╝████╗  ██║██╔════╝██╔════╝██╔════╝
# ██████╔╝█████╗  █████╗  █████╗  ██████╔╝█████╗  ██╔██╗ ██║██║     █████╗  ███████╗
# ██╔══██╗██╔══╝  ██╔══╝  ██╔══╝  ██╔══██╗██╔══╝  ██║╚██╗██║██║     ██╔══╝  ╚════██║
# ██║  ██║███████╗██║     ███████╗██║  ██║███████╗██║ ╚████║╚██████╗███████╗███████║
# ╚═╝  ╚═╝╚══════╝╚═╝     ╚══════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝ ╚═════╝╚══════╝╚══════╝

references:
  projectWorkspace: &projectWorkspace ~/myStocksRN
  androidWorkspace: &androidWorkspace ~/myStocksRN/android
  saveYarnLockfile: &saveYarnLockfile
    save_cache:
      name: Save yarn.lock file
      key: yarn-v1-{{ checksum "~/myStocksRN/yarn.lock" }}-{{ arch }}
      paths:
        - ~/.cache/yarn
  saveNodeModules: &saveNodeModules
    save_cache:
      name: Save node_modules
      key: node-v1-{{ checksum "~/myStocksRN/package.json" }}-{{ arch }}
      paths:
        - ~/myStocksRN/node_modules
  restoreYarnLockfile: &restoreYarnLockfile
    restore_cache:
      name: Restore yarn lock file
      key: yarn-v1-{{ checksum "~/myStocksRN/yarn.lock" }}-{{ arch }}
  restoreNodeModules: &restoreNodeModules
    restore_cache:
      name: Restore node_modules
      key: node-v1-{{ checksum "~/myStocksRN/package.json" }}-{{ arch }}

  #  +-+-+-+-+-+-+-+ +-+-+-+-+-+-+-+-+-+-+
  #  |a n d r o i d   r e f e r e n c e s|
  #  +-+-+-+-+-+-+-+ +-+-+-+-+-+-+-+-+-+-+
  android_config: &android_config
    working_directory: *androidWorkspace
    docker:
      - image: circleci/android:api-28-ndk
    environment:
      TERM: dumb
      _JAVA_OPTIONS: '-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap'
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'
  ruby_dependencies: &ruby_dependencies
    run:
      name: Download Ruby Dependencies
      command: bundle check || bundle install --path vendor/bundle
  android_dependencies: &android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies
  gradle_key: &gradle_key jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
  gems_key: &gems_key gems-{{ checksum "Gemfile.lock" }}
  save_gradle_cache: &save_gradle_cache
    save_cache:
      name: Save Gradle cache
      key: *gradle_key
      paths:
        - ~/.gradle
        - ~/.m2
  save_gems_cache: &save_gems_cache
    save_cache:
      name: Save Ruby Gems cache
      key: *gems_key
      paths:
        - ~/myStocksRN/android/vendor/bundle
  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      name: Restore Gradle cache
      key: *gradle_key
  restore_gems_cache: &restore_gems_cache
    restore_cache:
      name: Restore Ruby Gems cache
      key: *gems_key
  create_keystore_properties: &create_keystore_properties
    run:
      name: Create Android keystore properties file
      command: |
        printf 'RELEASE_KEY_STORE=%s\n' $RELEASE_KEY_STORE >> ~/myStocksRN/android/release-keystore.properties
        printf 'RELEASE_KEY_ALIAS_NAME=%s\n' $RELEASE_KEY_ALIAS_NAME >> ~/myStocksRN/android/release-keystore.properties
        printf 'RELEASE_KEY_ALIAS_PASSWORD=%s\n' $RELEASE_KEY_ALIAS_PASSWORD >> ~/myStocksRN/android/release-keystore.properties
        printf 'RELEASE_KEY_STORE_PASSWORD=%s\n' $RELEASE_KEY_STORE_PASSWORD >> ~/myStocksRN/android/release-keystore.properties
  decode_android_key: &decode_android_key
    run:
      name: Decode Android key store
      command: echo $KEYSTORE | base64 -d | tee keystore ~/myStocksRN/android/app/release.keystore > /dev/null

# --------------------------------------------------------------------------------------------------
#
#      ██╗ ██████╗ ██████╗ ███████╗
#      ██║██╔═══██╗██╔══██╗██╔════╝
#      ██║██║   ██║██████╔╝███████╗
# ██   ██║██║   ██║██╔══██╗╚════██║
# ╚█████╔╝╚██████╔╝██████╔╝███████║
#  ╚════╝  ╚═════╝ ╚═════╝ ╚══════╝

jobs:
  node:
    working_directory: *projectWorkspace
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - *restoreYarnLockfile
      - *restoreNodeModules
      - run: yarn install
      - *saveYarnLockfile
      - *saveNodeModules
      - persist_to_workspace:
          root: ~/myStocksRN
          paths:
            - node_modules
  lint:
    working_directory: *projectWorkspace
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - *restoreYarnLockfile
      - *restoreNodeModules
      - run: yarn lint
  test-node:
    working_directory: *projectWorkspace
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - *restoreYarnLockfile
      - *restoreNodeModules
      - run:
          name: jest tests
          command: |
            mkdir -p test-results
            yarn test
          environment:
            JEST_JUNIT_OUTPUT: test-results/junit/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - persist_to_workspace:
          root: ~/myStocksRN
          paths:
            - node_modules
  generate-android-release:
    <<: *android_config
    steps:
      - checkout:
          path: *projectWorkspace # checkout code in ~/myStocksRN , but cd to dir ~/myStocksRN
      - *restoreYarnLockfile
      - *restoreNodeModules
      - run:
          name: pwd && ls -lah ~/myStocksRN
          command: pwd && ls -lah ~/myStocksRN
      - run:
          name: pwd && ls -lah
          command: pwd && ls -lah
      - *restore_gradle_cache
      - *restore_gems_cache
      - *ruby_dependencies
      - *create_keystore_properties
      - *decode_android_key
      - run:
          name: pwd && ls -lah
          command: pwd && ls -lah
      - run:
          name: Install NodeJS
          command: |
            curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - *android_dependencies
      - *save_gradle_cache
      - *save_gems_cache
      - run:
          name: Generate Android Release APK build
          command: bundle exec fastlane assemble_release_build
      - store_artifacts:
          path: app/build/outputs/apk/
      - store_test_results:
          path: app/build/report/

# --------------------------------------------------------------------------------------------------
# ██╗    ██╗ ██████╗ ██████╗ ██╗  ██╗███████╗██╗      ██████╗ ██╗    ██╗
# ██║    ██║██╔═══██╗██╔══██╗██║ ██╔╝██╔════╝██║     ██╔═══██╗██║    ██║
# ██║ █╗ ██║██║   ██║██████╔╝█████╔╝ █████╗  ██║     ██║   ██║██║ █╗ ██║
# ██║███╗██║██║   ██║██╔══██╗██╔═██╗ ██╔══╝  ██║     ██║   ██║██║███╗██║
# ╚███╔███╔╝╚██████╔╝██║  ██║██║  ██╗██║     ███████╗╚██████╔╝╚███╔███╔╝
#  ╚══╝╚══╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚══════╝ ╚═════╝  ╚══╝╚══╝

workflows:
  version: 2
  build_android:
    jobs:
      - node
      - lint:
          requires:
            - node
      - test-node:
          requires:
            - lint
      - generate-android-release:
          requires:
            - test-node
