version: 2.1

# ██████╗ ███████╗███████╗███████╗██████╗ ███████╗███╗   ██╗ ██████╗███████╗███████╗
# ██╔══██╗██╔════╝██╔════╝██╔════╝██╔══██╗██╔════╝████╗  ██║██╔════╝██╔════╝██╔════╝
# ██████╔╝█████╗  █████╗  █████╗  ██████╔╝█████╗  ██╔██╗ ██║██║     █████╗  ███████╗
# ██╔══██╗██╔══╝  ██╔══╝  ██╔══╝  ██╔══██╗██╔══╝  ██║╚██╗██║██║     ██╔══╝  ╚════██║
# ██║  ██║███████╗██║     ███████╗██║  ██║███████╗██║ ╚████║╚██████╗███████╗███████║
# ╚═╝  ╚═╝╚══════╝╚═╝     ╚══════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝ ╚═════╝╚══════╝╚══════╝

references:
  projectWorkspace: &projectWorkspace ~/myStocksRN
  androidWorkspace: &androidWorkspace ~/myStocksRN/android
  saveYarnLockfile: &saveYarnLockfile
    save_cache:
      name: Save yarn.lock file
      key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
      paths:
        - ~/.cache/yarn
  saveNodeModules: &saveNodeModules
    save_cache:
      name: Save node_modules
      key: node-v1-{{ checksum "package.json" }}-{{ arch }}
      paths:
        - node_modules
  restoreYarnLockfile: &restoreYarnLockfile
    restore_cache:
      name: Restore yarn lock file
      key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
  restoreNodeModules: &restoreNodeModules
    restore_cache:
      name: Restore node_modules
      key: node-v1-{{ checksum "package.json" }}-{{ arch }}

# --------------------------------------------------------------------------------------------------
#
#      ██╗ ██████╗ ██████╗ ███████╗
#      ██║██╔═══██╗██╔══██╗██╔════╝
#      ██║██║   ██║██████╔╝███████╗
# ██   ██║██║   ██║██╔══██╗╚════██║
# ╚█████╔╝╚██████╔╝██████╔╝███████║
#  ╚════╝  ╚═════╝ ╚═════╝ ╚══════╝

jobs:
  node:
    working_directory: *projectWorkspace
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - *restoreYarnLockfile
      - *restoreNodeModules
      - run: yarn install
      - *saveYarnLockfile
      - *saveNodeModules
      - persist_to_workspace:
          root: ~/myStocksRN
          paths:
            - node_modules
  lint:
    working_directory: *projectWorkspace
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - *restoreYarnLockfile
      - *restoreNodeModules
      - run: yarn lint
  test-node:
    working_directory: *projectWorkspace
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - *restoreYarnLockfile
      - *restoreNodeModules
      - run:
          name: jest tests
          command: |
            mkdir -p test-results
            yarn test
          environment:
            JEST_JUNIT_OUTPUT: test-results/junit/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  # android:

# --------------------------------------------------------------------------------------------------
# ██╗    ██╗ ██████╗ ██████╗ ██╗  ██╗███████╗██╗      ██████╗ ██╗    ██╗
# ██║    ██║██╔═══██╗██╔══██╗██║ ██╔╝██╔════╝██║     ██╔═══██╗██║    ██║
# ██║ █╗ ██║██║   ██║██████╔╝█████╔╝ █████╗  ██║     ██║   ██║██║ █╗ ██║
# ██║███╗██║██║   ██║██╔══██╗██╔═██╗ ██╔══╝  ██║     ██║   ██║██║███╗██║
# ╚███╔███╔╝╚██████╔╝██║  ██║██║  ██╗██║     ███████╗╚██████╔╝╚███╔███╔╝
#  ╚══╝╚══╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚══════╝ ╚═════╝  ╚══╝╚══╝

workflows:
  version: 2
  build_android:
    jobs:
      - node
      - lint:
          requires:
            - node
      - test-node:
          requires:
            - lint
