# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  # desc "Submit a new Beta Build to Crashlytics Beta"
  # lane :beta do
  #   gradle(task: "clean assembleRelease")
  #   crashlytics
  
  #   # sh "your_script.sh"
  #   # You can also use other beta testing services here
  # end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end

  desc "Run Android Unit Tests"
  lane :unit_tests do |options|
    gradle(
      task: "test",
      build_type: options[:build_type]
    )
  end 

  # Generate Android APK for Debug and Release builds
  desc "Generate Android Debug and Release builds"
  lane :assemble_build do |options|
    gradle(
      task: "assemble",
      build_type: options[:build_type]
    )
  end

  # Generate Android APK for Debug build
  desc "Generate Android Debug build"
  lane :assemble_debug_build do |options|
    gradle(
      task: "assemble",
      build_type: 'debug'
    )
  end

  # Generate Android APK for Release build
  desc "Generate Android Release build"
  lane :assemble_release_build do |options|
    gradle(
      task: "assemble",
      build_type: 'release'
    )
  end
end
