# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  # Generate Android APK for Debug and Release builds
  desc "Generate Android Debug and Release builds"
  lane :assemble_build do |options|
    gradle(
      task: "assemble",
      build_type: options[:build_type]
    )
  end

  # Generate Android APK for Debug build
  desc "Generate Android Debug build"
  lane :assemble_debug_build do |options|
    gradle(
      task: "assemble",
      build_type: 'debug'
    )
  end

  # Generate Android APK for Release build
  desc "Generate Android Release build"
  lane :assemble_release_build do |options|
    gradle(
      task: "assemble",
      build_type: 'release'
    )
  end
end
