name: Release
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  YARN_MODULES_CACHE_KEY: v1
  YARN_PACKAGE_CACHE_KEY: v1
  YARN_CACHE_FOLDER: .cache/yarn
  FORCE_COLOR: true # display terminal colors

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

      - uses: actions/download-artifact@v2
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/

      - name: semantic-release
        if: github.ref == 'refs/heads/master'
        run: yarn semantic-release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
